### ISSUE TITLE
Where did you get this link from? (The API URL)

### ISSUE THREAD

**Issue by TUNA-NOPE** [ClydeTech/Audio-Pro-Player#1]
help

**Comment by ClydeTech** [comment]
Are you asking about the radio station URLs?
I got the BBC radio stream M3U8 URLs from here:
https://gist.github.com/bpsib/67089b959e4fa898af69fea59ad74bc3

If you are looking for AudioPro device API info, then you can check out this because they use audio boards made by LinkPlay
https://developer.arylic.com/httpapi/
